### ISSUE TITLE
Poissaolojen selvitys - Ei näppäintä - IOS 18.1

### ISSUE THREAD

**Issue by roopeimmonen** [wilmaplus/web-backend#1]
Sovelluksessa ei voi selvittää poissaoloja IOS 18.1 laitteella (tumma tila päällä). En tiedä mihin asia viittaa vai onko ominaisuutta edes lisätty, mutta mielestäni asia on oleellinen wilma sovelluksessa.

Voisitteko korjata?

Puhelin: iPhone 13 - IOS 18.1

**Comment by developerfromjokela** [comment]
Moi.
Sain kyllä sähköpostin, älä jatkossa avaa github issueita tänne kun tää ei oo sovelluksen repo
